import "katex/dist/katex.min.css";
import type { Metadata } from "next";
import "./globals.css";

import AmplifyConfigure from "./AmplifyConfigure";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="p-0 m-0">
        <AmplifyConfigure />
        {children}
      </body>
    </html>
  );
}
